version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: webui/backend/Dockerfile
    container_name: summit25_backend
    working_dir: /app
    command: ["flask", "run", "--host", "0.0.0.0"]
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: ./webui/frontend
      dockerfile: Dockerfile
    container_name: summit25_frontend
    ports:
      - "80:4200"
    working_dir: /app
    command: ["--host", "0.0.0.0", "--port", "80"]
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BACKEND_URL=http://localhost:5000
    network_mode: host
