version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: webui/backend/Dockerfile
    container_name: summit25_backend
    ports:
      - "5000:5000"
    working_dir: /app
    command: ["python3", "app.py"]
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: ./webui/frontend
      dockerfile: Dockerfile
    container_name: summit25_frontend
    ports:
      - "80:4200"
    working_dir: /app
    command: ["npm", "start", "--", "--host", "0.0.0.0"]
    environment:
      - CHOKIDAR_USEPOLLING=true
