deadline: "2025-05-22T13:00:00+03:00"
#wikipedia:
#  dump: "../../wikipedia/enwiki-latest-pages-articles-multistream.xml.bz2"
  #index: "../../wikipedia/enwiki-latest-pages-articles-multistream-index.txt.bz2"
#  index: "../../wikipedia/new_index.bin"
alternator:
  #endpoint_url: "http://localhost:8000"
text-search:
  endpoint_url: "http://localhost:6080"
